#!/usr/bin/env bash
set -euo pipefail

publish_workflow=".github/workflows/publish-images.yml"
promote_workflow=".github/workflows/promote-runtime.yml"

test -f "${publish_workflow}"
grep -q "workflow_dispatch:" "${publish_workflow}"
! grep -q "^[[:space:]]*push:" "${publish_workflow}"
grep -q "id-token: write" "${publish_workflow}"
grep -q "google-github-actions/auth" "${publish_workflow}"
grep -q "docker/login-action" "${publish_workflow}"
grep -q "docker/build-push-action" "${publish_workflow}"
grep -q "steps.auth.outputs.access_token" "${publish_workflow}"
! grep -q "steps.auth.outputs.auth_token" "${publish_workflow}"
grep -q "asia-south1-docker.pkg.dev" "${publish_workflow}"
! grep -q "terraform apply" "${publish_workflow}"
! grep -q "kubectl apply" "${publish_workflow}"

test -f "${promote_workflow}"
grep -q "workflow_dispatch:" "${promote_workflow}"
! grep -q "workflow_run:" "${promote_workflow}"
! grep -q "Publish Images" "${promote_workflow}"
! grep -q "head_branch == 'main'" "${promote_workflow}"
! grep -q "^[[:space:]]*push:" "${promote_workflow}"
grep -q "google-github-actions/auth" "${promote_workflow}"
grep -q "google-github-actions/get-gke-credentials" "${promote_workflow}"
grep -q "make runtime-image-check" "${promote_workflow}"
grep -q "make runtime-promote-latest" "${promote_workflow}"
grep -q "make runtime-promote-sha" "${promote_workflow}"
grep -q "make runtime-health" "${promote_workflow}"
grep -q "make public-demo-smoke" "${promote_workflow}"
grep -q "make grafana-public-apply" "${promote_workflow}"
grep -q "make grafana-public-smoke" "${promote_workflow}"
grep -q "GRAFANA_ADMIN_PASSWORD" "${promote_workflow}"
! grep -q "AUTO_DEPLOY_PUBLIC_GRAFANA" "${promote_workflow}"

echo "CI/CD workflows are manual-only; automatic image publish and runtime promotion are decommissioned."
