#!/usr/bin/env bash
set -euo pipefail

root_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
evidence_root="${RUNTIME_EVIDENCE_DIR:-artifacts/evidence}"
timestamp="$(date -u +%Y%m%dT%H%M%SZ)"
output_dir="${root_dir}/${evidence_root}/${timestamp}"
mkdir -p "${output_dir}"

capture() {
  local name="$1"
  shift
  {
    echo "$ $*"
    "$@"
  } > "${output_dir}/${name}.txt" 2>&1 || true
}

capture runtime-health "${root_dir}/infra/cloud/scripts/runtime_health.sh"
capture public-demo-status "${root_dir}/infra/cloud/scripts/public_demo_status.sh"
capture public-demo-url "${root_dir}/infra/cloud/scripts/public_demo_url.sh"
capture k8s-backup-check "${root_dir}/infra/cloud/scripts/k8s_backup_check.sh"
capture bigquery-cold-check "${root_dir}/infra/cloud/scripts/bigquery_cold_check.sh"
capture ci-publish-check "${root_dir}/infra/cloud/scripts/ci_publish_check.sh"
capture runtime-cost-report "${root_dir}/infra/cloud/scripts/runtime_cost_report.sh"

cat > "${output_dir}/README.md" <<EOF
# Runtime Evidence ${timestamp}

This folder contains sanitized command output for runtime review. It intentionally excludes secrets, .env files, Terraform state, kubeconfig, tokens, and credentials.

Generated by:

\`\`\`sh
make runtime-evidence
\`\`\`
EOF

echo "Runtime evidence written to ${output_dir}"
