apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: smartcity-grafana-backend
  namespace: __GKE_NAMESPACE__
spec:
  timeoutSec: 300
  healthCheck:
    type: HTTP
    requestPath: /api/health
    port: 3000
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smartcity-grafana-public
  namespace: __GKE_NAMESPACE__
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: __PUBLIC_GRAFANA_STATIC_IP_NAME__
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: smartcity-grafana
                port:
                  number: 3000
