apiVersion: v1
kind: Namespace
metadata:
  name: smartcity
  labels:
    app.kubernetes.io/name: smartcity-zero-disk
    app.kubernetes.io/part-of: smartcity-zero-disk
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: smartcity-readiness-quota
  namespace: smartcity
spec:
  hard:
    pods: "20"
    requests.cpu: "8"
    requests.memory: 16Gi
