apiVersion: v1
kind: ServiceAccount
metadata:
  name: smartcity-ingestor
  namespace: smartcity
  annotations:
    iam.gke.io/gcp-service-account: smartcity-ingestor@replace-me-project.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: smartcity-writer
  namespace: smartcity
  annotations:
    iam.gke.io/gcp-service-account: smartcity-writer@replace-me-project.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: smartcity-analytics
  namespace: smartcity
  annotations:
    iam.gke.io/gcp-service-account: smartcity-analytics@replace-me-project.iam.gserviceaccount.com
