apiVersion: v1
kind: ServiceAccount
metadata:
  name: smartcity-ingestor
  namespace: __GKE_NAMESPACE__
  annotations:
    iam.gke.io/gcp-service-account: smartcity-ingestor@__GCP_PROJECT_ID__.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: smartcity-writer
  namespace: __GKE_NAMESPACE__
  annotations:
    iam.gke.io/gcp-service-account: smartcity-writer@__GCP_PROJECT_ID__.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: smartcity-analytics
  namespace: __GKE_NAMESPACE__
  annotations:
    iam.gke.io/gcp-service-account: smartcity-analytics@__GCP_PROJECT_ID__.iam.gserviceaccount.com
